apiVersion: v1
kind: Service
metadata:
  labels:
    service: neighborly-functions
  name: neighborly-functions
spec:
  ports:
  - name: "80"
    port: 80
     
  selector:
    service: neighborly-functions
  type: LoadBalancer    